---
- name: Dodawanie usra panda w grupie panda
  group:
    name: panda
    state: present
- name: dodawanie usera panda w gupie panda
  user:
    name: panda
    shell: /bin/bash
    state: present
    groups: 
      - panda
      - sudo
- name: kopiowanie klucza
  authorized_key:
    user: panda
    state: present
    key: "{{ lookup('file', '/home/vagrant/.ssh/authorized_keys') }}"
